### ISSUE TITLE
Parametrize azure and graph endpoint

### ISSUE THREAD

**Issue by trobiyo** [CERN/msgraph-poll-discourse-plugin#5]
It would be interesting to have https://github.com/CERN/msgraph-poll-discourse-plugin/blob/master/plugin.rb#L22 , https://github.com/CERN/msgraph-poll-discourse-plugin/blob/master/lib/validators/msgraph_poll_settings_validator.rb#L16 and https://github.com/CERN/msgraph-poll-discourse-plugin/blob/master/lib/validators/msgraph_poll_settings_validator.rb#L32 parametrized through the UI, same as the token.

It is true that urls are not meant to change in the short-term, but in the event of a change, this can be easily reconfigurable.

**Comment by AlessioC31** [comment]
![image](https://github.com/CERN/msgraph-poll-discourse-plugin/assets/5256712/7ac5a46f-ef37-4dee-a2d0-d680506b0f4d)

So do you suggest to remove the tenant id from settings and putting the entire auth url as a setting?

**Comment by trobiyo** [comment]
In my opinion, I would do it as follows:

auth_url =
"#{SiteSetting.azure_ad_endpoint_or_the_name_you_want_to_use}/#{SiteSetting.msgraph_polling_tenant_id}/oauth2/v2.0/token"

You can get inspiration about how GitLab does it through
https://gitlab.com/gitlab-org/gitlab/-/blob/master/vendor/gems/microsoft_graph_mailer/spec/spec_helper.rb#L22

**Comment by trobiyo** [comment]
Done in https://github.com/CERN/msgraph-poll-discourse-plugin/commit/456672466259901626428a4c42e3af4aaa3daeb6

Awesome 👏
